server:
  port: 8700
spring:
  application:
    name: eureka-01
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?setUnicode=true&characterEncoding=utf8
    data-username: root
    data-password: huhuwang3
eureka:
  instance:
    hostname: localhost #服务注册中心IP地址
  client:
    registerWithEureka: false #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/