server:
  port: 8810
spring:
  application:
    name: Time-01
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?setUnicode=true&characterEncoding=utf8
    data-username: root
    data-password: huhuwang3
#  redis:
#    host: 192.168.133.136
#    port: 6380
#    jedis:
#      pool:
#        max-wait: 50000
#        max-active: 100
#        max-idle: 20
#        min-idle: 0
#    timeout: 3000